package com.houseofdolswe.HouserOfDolswe_server.domain.enums;

public enum Age {
	TEENS_EARLY, TEENS_MID, TEENS_LATE, TWENTIES_EARLY, TWENTIES_MID, TWENTIES_LATE,
	THIRTIES_EARLY, THIRTIES_MID, THIRTIES_LATE, FORTIES_EARLY, FORTIES_MID, FORTIES_LATE,
	FIFTIES_EARLY, FIFTIES_MID, FIFTIES_LATE, SIXTIES_PLUS
}
